### ISSUE TITLE
Brightness not working after update to Mojave

### ISSUE THREAD

**Issue by superzeldalink** [aytic/Lenovo-Flex-2-15-Hackintosh#3]

**Comment by aytic** [comment]
You probably forgot to add things in our patched folder.. If not provide a link to your problem reporting files. Please use this tool: https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/

**Comment by superzeldalink** [comment]
I have added 4 files from your repository, you can see the image in the link below
https://imgur.com/gallery/0nuWuq9
If you need the reporting files, I will send you tomorrow. 
Thanks for helping :)

**Comment by aytic** [comment]
Hm ok, provide me with the .zip please :)

**Comment by superzeldalink** [comment]
Here is the zip file:
https://drive.google.com/open?id=1_TiZ7qj7-9D6VrgZ_6-OgugLAjX00heJ

**Comment by aytic** [comment]
Your kexts are not installed properly (should not be on EFI Partition). Also there is a conflicting kext. Are you using the Brightness Control with or without Fn keys? Does brightness control work in general? If yes you need to probably check what your ACPI Events are https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/

**Comment by superzeldalink** [comment]
Yes, I'm installed. I've done all the things but still not working

**Comment by aytic** [comment]
I assume it is caused by your Clover Setup. Backup your folder and try with a fresh setup (use rehabmans latest clover). Please setup Clover properly (you are using 3 different OsxAptioFix). They are not meant to be used in that way and can cause failure.

**Comment by aytic** [comment]
No Problem Reporting files attached.
